env:
    _target_: "BipedalWalker-v3"
    gym: True
    discrete: False # Discrete action space

expert_hyperparams:
    num_iters: 1000
    num_steps_per_iter: 5000
    horizon: null
    render_gif: False

training_hyperparams:
    num_iters: 1000
    num_steps_per_iter: 5000
    horizon: null
    lr: 1e-3
    ce_lambda: 1e-3
    gae_gamma: 0.99
    gae_lambda: 0.99
    epsilon: 0.01
    max_kl: 0.01
    cg_damping: 0.1
    normalize_advantage: True

algo:
    toy: False
    algo: "GAIL"

expert_net:
    _target_: src.agent_networks.gail_networks.Expert

policy_net:
    _target_: src.agent_networks.gail_networks.PolicyNetwork

value_net:
    _target_: src.agent_networks.gail_networks.ValueNetwork

discriminator_net:
    _target_: src.agent_networks.gail_networks.Discriminator

# Wandb settings
wandb:
    project: HCC_NG_vs_TBS
    job_type: bipedal
    tags: [NG_vs_TBS]
    mode: online # Whether to use wandb [disabled, online]
    run_name: null
