env:
    _target_: "CartPole-v1"
    gym: True
    discrete: True # Discrete action space.

expert_hyperparams:
    num_iters: 200
    num_steps_per_iter: 2000
    horizon: null
    render_gif: False

training_hyperparams:
    num_iters: 200
    num_steps_per_iter: 2000
    horizon: null
    lr: 1e-3
    ce_lambda: 1e-2
    gae_gamma: 0.99
    gae_lambda: 0.99
    epsilon: 0.01
    max_kl: 0.01
    cg_damping: 0.1
    normalize_advantage: True
    # The following are discriminator hyperparams.
    disc_opt_method: "TBS" # Use GAIL or TBS
    disc_tbs_method: "optimistic" # use optimistic or standard
    disc_inner_loops: 20
    disc_eta: 3e-1
    # The following are value hyperparams
    value_inner_loops: 20
    value_grad_max_norm: 10.0
    # The following are agent's policy hyperparameters
    policy_opt_method: "TBS" # Use GAIL or TBS
    policy_tbs_method: "optimistic" # use optimistic or standard
    policy_inner_loops: 20
    policy_eta: 3e-1

algo:
    toy: False
    algo: "GAIL"

expert_net:
    _target_: src.agent_networks.gail_networks.Expert

policy_net:
    _target_: src.agent_networks.gail_networks.PolicyNetwork

value_net:
    _target_: src.agent_networks.gail_networks.ValueNetwork

discriminator_net:
    _target_: src.agent_networks.gail_networks.Discriminator

# Wandb settings
wandb:
    project: GAIL_cartpole
    job_type: cartpole
    tags: [HCC_Project]
    mode: online # Whether to use wandb [disabled, online].
    run_name: null
