


algo:
    algo: "ng"

training_hyperparams:
    num_steps: 1000
    base_lr: 1e-5
    lr_schedule: True


# Wandb settings
wandb:
    project: HCC_NG_vs_TBS
    tags: [NG_vs_TBS]
    mode: online # Whether to use wandb [disabled, online]
    run_name: None
